// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9difbtFhtIkXTrXYjEMIYHvflJpBr4TM',
    appId: '1:935820746869:android:27d4737a44d2a332b6d83c',
    messagingSenderId: '935820746869',
    projectId: 'trusted-wifi-finder',
    storageBucket: 'trusted-wifi-finder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-tKS0Dp0lfs0LP_pDuc5rEvC8UvdrjjM',
    appId: '1:935820746869:ios:bc7a56b5727ff965b6d83c',
    messagingSenderId: '935820746869',
    projectId: 'trusted-wifi-finder',
    storageBucket: 'trusted-wifi-finder.firebasestorage.app',
    iosBundleId: 'com.example.trustedWifiFinder',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4-AUaoJPdiP6f8NrYuFNhSOFzDKpl8YY',
    appId: '1:935820746869:web:8aadf38d62b0cbf2b6d83c',
    messagingSenderId: '935820746869',
    projectId: 'trusted-wifi-finder',
    authDomain: 'trusted-wifi-finder.firebaseapp.com',
    storageBucket: 'trusted-wifi-finder.firebasestorage.app',
    measurementId: 'G-GLZTZFJLE8',
  );

}